import {
  AdminCertificate,
  Coupon,
  AdminNotification,
  AdminActivityLog,
  WebsiteContent,
  AdminSettings,
} from './admin-types';

export const MOCK_COUPONS: Coupon[] = [
  {
    id: 'coupon-mock-1',
    code: 'SKILL100',
    description: 'State Sponsored 100% Tuition Fee Waiver',
    discountType: 'percentage',
    discountValue: 100,
    expiresAt: '2027-12-31',
    validFrom: null,
    maxUses: 200,
    usedCount: 42,
    perUserLimit: 1,
    minAmount: null,
    courseId: null,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'coupon-mock-2',
    code: 'MAHA50',
    description: 'Civil Welfare Discount 50% Off',
    discountType: 'percentage',
    discountValue: 50,
    expiresAt: '2027-06-30',
    validFrom: null,
    maxUses: 100,
    usedCount: 18,
    perUserLimit: 1,
    minAmount: 1000,
    courseId: null,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'coupon-mock-3',
    code: 'AGRIFREE',
    description: 'Agricultural Specialization full scholarship',
    discountType: 'fixed',
    discountValue: 4000,
    expiresAt: '2026-12-31',
    validFrom: null,
    maxUses: 50,
    usedCount: 12,
    perUserLimit: 1,
    minAmount: null,
    courseId: 'c-301',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'coupon-mock-4',
    code: 'EXPIRED10',
    description: 'Early Tester 10% coupon',
    discountType: 'percentage',
    discountValue: 10,
    expiresAt: '2026-05-01',
    validFrom: null,
    maxUses: 30,
    usedCount: 30,
    perUserLimit: 1,
    minAmount: null,
    courseId: null,
    isActive: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_CERTIFICATES: AdminCertificate[] = [
  {
    id: 'cert-601',
    course_id: 'c-301',
    member_id: 'mem-101',
    certificate_no: 'MH-SKILL-2026-11942',
    issue_date: '2026-07-15',
    status: 'generated',
  },
  {
    id: 'cert-602',
    course_id: 'c-301',
    member_id: 'mem-108',
    certificate_no: 'MH-SKILL-2026-78322',
    issue_date: '2026-07-14',
    status: 'accepted',
  },
];

export const MOCK_NOTIFICATIONS: AdminNotification[] = [
  {
    id: 'notif-701',
    title: 'Monsoon Agro Training Commences',
    description: 'Classes for Organic Farming begin on August 1st at Satara Center.',
    icon: 'Calendar',
    target: 'All Members',
    created_at: '2026-07-15 10:30',
  },
  {
    id: 'notif-702',
    title: 'UI/UX Access Codes Issued',
    description: 'Please check your registered WhatsApp or SMS for custom enrollment passcode key.',
    icon: 'Award',
    target: 'All Members',
    created_at: '2026-07-14 16:45',
  },
  {
    id: 'notif-703',
    title: 'Urgent Aadhaar Verification Alert',
    description: 'Several records have mismatched civil data. Please re-upload your primary id scan copy.',
    icon: 'Bell',
    target: 'Group',
    created_at: '2026-07-12 09:15',
  },
];

export const MOCK_ACTIVITY_LOGS: AdminActivityLog[] = [
  {
    id: 'act-801',
    title: 'Beneficiary Registered',
    description: 'Admin registered Meera Gavit from Dhadgaon village to NGO Database.',
    timestamp: '10 minutes ago',
    icon: 'Users',
  },
  {
    id: 'act-802',
    title: 'Course Updated',
    description: 'Instructor Savita Phadke updated syllabus for UI/UX Web Design.',
    timestamp: '2 hours ago',
    icon: 'BookOpen',
  },
  {
    id: 'act-803',
    title: 'Coupon Activated',
    description: "System created and activated sponsor coupon code: 'AGRIFREE'.",
    timestamp: '1 day ago',
    icon: 'Award',
  },
  {
    id: 'act-804',
    title: 'Member Enrollment Modified',
    description: "Admin shifted Sanjay Shinde state program state to 'Inactive'.",
    timestamp: '2 days ago',
    icon: 'Bell',
  },
  {
    id: 'act-805',
    title: 'Security Rules Hardened',
    description: 'Enforced mandatory alphanumeric password requirements for teacher accounts.',
    timestamp: '3 days ago',
    icon: 'Users',
  },
];

export const MOCK_WEBSITE_CONTENT: WebsiteContent = {
  courses: [
    { id: 'web-c1', title: 'Organic Cultivation Course', description: 'Our flag agricultural training modules.', visibility: 'Both Pages', image: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&q=80&w=400' },
    { id: 'web-c2', title: 'Figma & Layout Mastery', description: 'Learn web and application layouts with visual balance.', visibility: 'Homepage Only', image: 'https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?auto=format&fit=crop&q=80&w=400' },
  ],
  programs: [
    { id: 'web-p1', title: 'Satara Rural Skills Enhancement Program', description: 'Funded by state sponsorship initiatives.', visibility: 'Both Pages' },
    { id: 'web-p2', title: 'Women Vocational Empowerment Drive', description: 'Free tailoring and retailing modules in Sangli district.', visibility: 'Programs Page Only' },
  ],
  leadership: [
    { id: 'web-l1', title: 'Shri. Prakash Deshmukh', description: 'Executive Director & NGO Founder', visibility: 'Both Pages' },
    { id: 'web-l2', title: 'Smt. Shaila Patil', description: 'Rural Education Coordinator', visibility: 'Both Pages' },
  ],
  testimonials: [
    { id: 'web-t1', title: 'Priya Patil', description: 'This course completely transformed my outlook. I earned state placement!', visibility: 'Both Pages' },
    { id: 'web-t2', title: 'Vijay Rathod', description: 'The organic farming guidelines helped us increase output by 20%. Thank you, Compassion!', visibility: 'Homepage Only' },
  ],
  contact_social: {
    address: 'Plot 42, Civil Lines, Behind Satara Court, Satara, Maharashtra - 415001',
    email: 'contact@compassionglobal.org',
    phone: '+91 2162 234567',
    facebook: 'https://facebook.com/compassionglobal',
    twitter: 'https://twitter.com/compassionglb',
    linkedin: 'https://linkedin.com/company/compassionglobal',
    instagram: 'https://instagram.com/compassionglobal',
  },
  gallery: [
    { id: 'web-g1', title: 'Farming Workshop 2026', visibility: 'Homepage Only' },
    { id: 'web-g2', title: 'Graduation Ceremony Batch A', visibility: 'Both Pages' },
  ],
  resources: [
    { id: 'web-r1', title: 'NGO Brochure PDF', description: 'Complete organizational brief.', visibility: 'Both Pages' },
    { id: 'web-r2', title: 'Organic Farming Quick Guide', description: 'Composting manual in Marathi/Hindi.', visibility: 'Both Pages' },
  ],
  locations: [
    { id: 'web-loc1', title: 'Satara Krishi Center', description: 'Rural farm and hybrid coaching space.', visibility: 'Both Pages' },
    { id: 'web-loc2', title: 'Nandurbar Paramedic Clinic', description: 'Healthcare lab setup.', visibility: 'Both Pages' },
  ],
};

export const DEFAULT_ADMIN_SETTINGS: AdminSettings = {
  general: {
    siteName: 'CompassionGlobal NGO Portal',
    description: 'Empowering rural youth and farmers with modern technological, agricultural, and business skills.',
    logo: 'CompassionGlobal',
    timezone: 'Asia/Kolkata (GMT+05:30)',
    language: 'en',
  },
  email: {
    smtpHost: 'smtp.compassionglobal.org',
    smtpPort: '587',
    smtpUser: 'noreply@compassionglobal.org',
    senderName: 'NGO Skill Coordinator',
    senderEmail: 'coordinator@compassionglobal.org',
    notifNewRegistration: true,
    notifApplication: true,
    notifCertificate: true,
  },
  security: {
    pwMinLength: 8,
    pwRequiresSpecial: true,
    pwRequiresNumber: true,
    pwRequiresUppercase: true,
    sessionTimeout: 30,
    maxLoginAttempts: 5,
    enable2FA: false,
  },
  appearance: {
    theme: 'Light',
    brandColor: '#2563EB',
    sidebarCollapsedDefault: false,
    fontSize: 'Medium',
  },
  system: {
    maintenanceMode: false,
    maintenanceMessage: 'System is undergoing a scheduled database synchronization backup. We will be online shortly.',
    autoBackup: true,
    backupFrequency: 'Daily',
    backupRetention: 30,
  },
};
