import {
  Member,
  Teacher,
  AdminCourse,
  Enrollment,
  AdminCertificate,
  Coupon,
  AdminNotification,
  AdminActivityLog,
  WebsiteContent,
  AdminSettings,
} from './admin-types';

export const MOCK_MEMBERS: Member[] = [
  {
    id: 'mem-101',
    full_name: 'Rohit Deshmukh',
    email: 'rohit.deshmukh@gmail.com',
    phone: '9876543210',
    age: 24,
    gender: 'Male',
    category: 'General',
    qualification: 'Graduate',
    village: 'Wai',
    district: 'Satara',
    state: 'Maharashtra',
    status: 'Active',
    assigned_volunteer: 'Amit Sharma',
    created_at: '2026-01-10',
  },
  {
    id: 'mem-102',
    full_name: 'Priya Patil',
    email: 'priya.patil@yahoo.com',
    phone: '8765432109',
    age: 22,
    gender: 'Female',
    category: 'OBC',
    qualification: '12th Pass',
    village: 'Karad',
    district: 'Satara',
    state: 'Maharashtra',
    status: 'Active',
    assigned_volunteer: 'Amit Sharma',
    created_at: '2026-02-15',
  },
  {
    id: 'mem-103',
    full_name: 'Sunita Kamble',
    email: 'sunita.k@gmail.com',
    phone: '7654321098',
    age: 29,
    gender: 'Female',
    category: 'SC',
    qualification: '10th Pass',
    village: 'Koregaon',
    district: 'Satara',
    state: 'Maharashtra',
    status: 'Active',
    assigned_volunteer: 'Sneha Patil',
    created_at: '2026-03-20',
  },
  {
    id: 'mem-104',
    full_name: 'Vijay Rathod',
    email: 'vijay.r@rediffmail.com',
    phone: '6543210987',
    age: 31,
    gender: 'Male',
    category: 'ST',
    qualification: 'Graduate',
    village: 'Shirala',
    district: 'Sangli',
    state: 'Maharashtra',
    status: 'Active',
    assigned_volunteer: 'Sneha Patil',
    created_at: '2026-04-05',
  },
  {
    id: 'mem-105',
    full_name: 'Anjali Joshi',
    email: 'anjali.joshi@outlook.com',
    phone: '9123456780',
    age: 20,
    gender: 'Female',
    category: 'General',
    qualification: '12th Pass',
    village: 'Tasgaon',
    district: 'Sangli',
    state: 'Maharashtra',
    status: 'Active',
    assigned_volunteer: 'Amit Sharma',
    created_at: '2026-04-12',
  },
  {
    id: 'mem-106',
    full_name: 'Sanjay Shinde',
    email: 'sanjay.s@gmail.com',
    phone: '9234567801',
    age: 27,
    gender: 'Male',
    category: 'General',
    qualification: '10th Pass',
    village: 'Miraj',
    district: 'Sangli',
    state: 'Maharashtra',
    status: 'Inactive',
    assigned_volunteer: 'Karan Johar',
    created_at: '2026-05-01',
  },
  {
    id: 'mem-107',
    full_name: 'Meera Gavit',
    email: 'meera.gavit@gmail.com',
    phone: '9345678012',
    age: 26,
    gender: 'Female',
    category: 'ST',
    qualification: 'Graduate',
    village: 'Dhadgaon',
    district: 'Nandurbar',
    state: 'Maharashtra',
    status: 'Active',
    assigned_volunteer: 'Vikram Singh',
    created_at: '2026-05-18',
  },
  {
    id: 'mem-108',
    full_name: 'Rahul More',
    email: 'rahul.more@gmail.com',
    phone: '9456780123',
    age: 25,
    gender: 'Male',
    category: 'OBC',
    qualification: 'Post Graduate',
    village: 'Shahada',
    district: 'Nandurbar',
    state: 'Maharashtra',
    status: 'Active',
    assigned_volunteer: 'Vikram Singh',
    created_at: '2026-06-02',
  },
];

export const MOCK_TEACHERS: Teacher[] = [
  {
    id: 't-201',
    full_name: 'Dr. Aniruddha Kulkarni',
    email: 'aniruddha.k@compassion.org',
    phone: '9811223344',
    designation: 'Senior Instructor',
    type: 'Full Time',
    status: 'Active',
    join_date: '2024-06-15',
    district: 'Satara',
    specialization: 'Organic Farming & Agronomy',
    experience: '12 Years',
    qualification: 'Ph.D. in Agriculture',
    rating: 4.8,
  },
  {
    id: 't-202',
    full_name: 'Prof. Savita Phadke',
    email: 'savita.phadke@compassion.org',
    phone: '9822334455',
    designation: 'Lead Educator',
    type: 'Full Time',
    status: 'Active',
    join_date: '2025-01-10',
    district: 'Sangli',
    specialization: 'UI/UX & Frontend Technology',
    experience: '8 Years',
    qualification: 'M.Tech in CS',
    rating: 4.9,
  },
  {
    id: 't-203',
    full_name: 'Mr. Harish Sawant',
    email: 'harish.sawant@compassion.org',
    phone: '9833445566',
    designation: 'Assistant Teacher',
    type: 'Part Time',
    status: 'Active',
    join_date: '2025-08-01',
    district: 'Satara',
    specialization: 'Basic Tally & Accounting',
    experience: '4 Years',
    qualification: 'M.Com',
    rating: 4.5,
  },
  {
    id: 't-204',
    full_name: 'Mrs. Lalita Rane',
    email: 'lalita.rane@compassion.org',
    phone: '9844556677',
    designation: 'Healthcare Trainer',
    type: 'Part Time',
    status: 'Active',
    join_date: '2026-02-28',
    district: 'Nandurbar',
    specialization: 'Nursing & Maternal Healthcare',
    experience: '6 Years',
    qualification: 'B.Sc Nursing',
    rating: 4.7,
  },
];

export const MOCK_COUPONS: Coupon[] = [
  {
    code: 'SKILL100',
    description: 'State Sponsored 100% Tuition Fee Waiver',
    type: 'Percentage',
    value: 100,
    expiry_date: '2027-12-31',
    max_uses: 200,
    uses_count: 42,
    per_user_limit: 1,
    min_order_value: 0,
    course_id: 'global',
    status: 'Active',
  },
  {
    code: 'MAHA50',
    description: 'Civil Welfare Discount 50% Off',
    type: 'Percentage',
    value: 50,
    expiry_date: '2027-06-30',
    max_uses: 100,
    uses_count: 18,
    per_user_limit: 1,
    min_order_value: 1000,
    course_id: 'global',
    status: 'Active',
  },
  {
    code: 'AGRIFREE',
    description: 'Agricultural Specialization full scholarship',
    type: 'Fixed',
    value: 4000,
    expiry_date: '2026-12-31',
    max_uses: 50,
    uses_count: 12,
    per_user_limit: 1,
    min_order_value: 0,
    course_id: 'c-301',
    status: 'Active',
  },
  {
    code: 'EXPIRED10',
    description: 'Early Tester 10% coupon',
    type: 'Percentage',
    value: 10,
    expiry_date: '2026-05-01',
    max_uses: 30,
    uses_count: 30,
    per_user_limit: 1,
    min_order_value: 0,
    course_id: 'global',
    status: 'Inactive',
  },
];

export const MOCK_COURSES: AdminCourse[] = [
  {
    id: 'c-301',
    title: 'Organic Agricultural Practice & Farming',
    category: 'Agriculture',
    mode: 'Offline',
    location: 'Satara Krishi Kendra',
    teacher_id: 't-201',
    start_date: '2026-08-01',
    end_date: '2026-11-01',
    duration: '12 Weeks',
    seats_total: 40,
    seats_enrolled: 25,
    access_code_required: false,
    auto_approve: true,
    price: 4000,
    currency: 'INR',
    coupons: [],
    required_docs: ['Aadhaar', 'Ration Card'],
    syllabus: [
      { id: 'les-1', title: 'Introduction to Soil Health & pH Management', type: 'Video', duration: '1h 30m' },
      { id: 'les-2', title: 'Bio-fertilizers: Composting & Neem Formulation', type: 'Text', duration: '2 Hours' },
      { id: 'les-3', title: 'Water Conservation & Drip Irrigation Systems', type: 'Assignment', duration: '3 Hours' },
      { id: 'les-4', title: 'First-term Agricultural Soil Assessment Test', type: 'Quiz', duration: '45 Mins' },
    ],
    status: 'Published',
    meta_description: 'Learn traditional and scientific ways of modern organic composting and agricultural yield enhancement.',
    benefits: ['Understand soil bio-dynamics', 'Prepare non-chemical bio-pesticides', 'Unlock state farm subsidies'],
    eligibility: 'Farmers or rural youth looking to learn organic cultivation methods. Minimum 10th standard preferred.',
  },
  {
    id: 'c-302',
    title: 'UI/UX Web Design & Frontend Development Fundamentals',
    category: 'Tech',
    mode: 'Hybrid',
    location: 'Satara Main Office & Zoom',
    teacher_id: 't-202',
    start_date: '2026-08-15',
    end_date: '2026-12-15',
    duration: '16 Weeks',
    seats_total: 30,
    seats_enrolled: 18,
    access_code_required: true,
    auto_approve: false,
    price: 12000,
    currency: 'INR',
    coupons: [],
    required_docs: ['Aadhaar', 'Profile Photo'],
    syllabus: [
      { id: 'les-5', title: 'Visual Design: Grid, Layouts & Color Theory', type: 'Video', duration: '2 Hours' },
      { id: 'les-6', title: 'Figma Prototyping: Interactive States & Flows', type: 'Video', duration: '3 Hours' },
      { id: 'les-7', title: 'Tailwind CSS & Responsive Styling Integration', type: 'Assignment', duration: '5 Hours' },
      { id: 'les-8', title: 'Final Design Portfolio Case Study Submission', type: 'Assignment', duration: '8 Hours' },
    ],
    status: 'Published',
    meta_description: 'Master modern design layouts, user journey maps, wireframing, and HTML/CSS styling integration.',
    benefits: ['Build an end-to-end design portfolio', 'Learn responsive UI layout structures', 'Direct internship placements'],
    eligibility: 'Enthusiasts seeking careers in web/app designing. Requires a standard personal laptop.',
  },
  {
    id: 'c-303',
    title: 'Healthcare Assistant & Primary First-Aid Training',
    category: 'Healthcare',
    mode: 'Offline',
    location: 'Nandurbar Community Clinic',
    teacher_id: 't-204',
    start_date: '2026-09-01',
    end_date: '2026-11-01',
    duration: '8 Weeks',
    seats_total: 25,
    seats_enrolled: 12,
    access_code_required: false,
    auto_approve: true,
    price: 3000,
    currency: 'INR',
    coupons: [],
    required_docs: ['Aadhaar', 'PAN'],
    syllabus: [
      { id: 'les-9', title: 'Vitals Recording: BP, SpO2 & Temperature Checks', type: 'Video', duration: '1h 15m' },
      { id: 'les-10', title: 'Wound Management & Sterilization Standards', type: 'Text', duration: '1 Hour' },
      { id: 'les-11', title: 'Emergency Cardiopulmonary Resuscitation (CPR)', type: 'Assignment', duration: '2 Hours' },
    ],
    status: 'Published',
    meta_description: 'Essential training to assist registered nurses, conduct standard health tests, and provide emergency aid.',
    benefits: ['Sponsorship certificate from local hospitals', 'Master life-saving emergency medical skills', 'Free paramedic kit provided'],
    eligibility: 'Compassionate individuals ready to serve local rural clinics. Minimum 12th standard pass in science/arts.',
  },
  {
    id: 'c-304',
    title: 'Tally ERP & Accounting Basics for Retailers',
    category: 'Business',
    mode: 'Online',
    location: 'Compassion Online LMS',
    teacher_id: 't-203',
    start_date: '2026-07-25',
    end_date: '2026-09-25',
    duration: '8 Weeks',
    seats_total: 50,
    seats_enrolled: 32,
    access_code_required: false,
    auto_approve: true,
    price: 2500,
    currency: 'INR',
    coupons: [],
    required_docs: ['Aadhaar'],
    syllabus: [
      { id: 'les-12', title: 'Introduction to Double Entry & Ledgers', type: 'Video', duration: '1 Hour' },
      { id: 'les-13', title: 'GST Ledger Creation & Voucher Recording', type: 'Video', duration: '2 Hours' },
      { id: 'les-14', title: 'Bank Reconciliation Statement (BRS)', type: 'Quiz', duration: '30 Mins' },
    ],
    status: 'Draft',
    meta_description: 'Learn Tally Prime to manage cash journals, ledgers, inventory, and monthly GST filing for shops.',
    benefits: ['Accounting competence certificate', 'Hands-on virtual ledger software trials', 'Eligible for micro-retailer loans'],
    eligibility: 'Small business owners, retail operators, or fresh graduates looking to build book-keeping careers.',
  },
];

export const MOCK_ENROLLMENTS: Enrollment[] = [
  {
    id: 'enr-501',
    member_id: 'mem-101',
    course_id: 'c-301',
    enrolled_date: '2026-06-25',
    status: 'Completed',
    doc_verified: true,
    admin_notes: 'Regular attendance. Exceeded syllabus parameters. Ready for certificate issuance.',
  },
  {
    id: 'enr-502',
    member_id: 'mem-102',
    course_id: 'c-302',
    enrolled_date: '2026-06-28',
    status: 'Enrolled',
    doc_verified: true,
    admin_notes: 'Sponsor coupon SKILL100 applied correctly. Interview clear.',
  },
  {
    id: 'enr-503',
    member_id: 'mem-103',
    course_id: 'c-301',
    enrolled_date: '2026-07-02',
    status: 'Pending',
    doc_verified: false,
    admin_notes: 'Aadhaar document copy blurred. Needs clear resubmission.',
  },
  {
    id: 'enr-504',
    member_id: 'mem-104',
    course_id: 'c-301',
    enrolled_date: '2026-07-05',
    status: 'Enrolled',
    doc_verified: true,
    admin_notes: 'Approved. All civil verification cleared.',
  },
  {
    id: 'enr-505',
    member_id: 'mem-105',
    course_id: 'c-302',
    enrolled_date: '2026-07-10',
    status: 'Dropped',
    doc_verified: true,
    admin_notes: 'Requested withdrawal due to relocation to Pune.',
  },
  {
    id: 'enr-506',
    member_id: 'mem-107',
    course_id: 'c-303',
    enrolled_date: '2026-07-12',
    status: 'Pending',
    doc_verified: true,
    admin_notes: 'Docs matching completed. Waiting for final instructor seat confirmation.',
  },
];

export const MOCK_CERTIFICATES: AdminCertificate[] = [
  {
    id: 'cert-601',
    course_id: 'c-301',
    member_id: 'mem-101',
    certificate_no: 'MH-SKILL-2026-11942',
    issue_date: '2026-07-15',
    status: 'generated',
  },
  {
    id: 'cert-602',
    course_id: 'c-301',
    member_id: 'mem-108',
    certificate_no: 'MH-SKILL-2026-78322',
    issue_date: '2026-07-14',
    status: 'accepted',
  },
];

export const MOCK_NOTIFICATIONS: AdminNotification[] = [
  {
    id: 'notif-701',
    title: 'Monsoon Agro Training Commences',
    description: 'Classes for Organic Farming begin on August 1st at Satara Center.',
    icon: 'Calendar',
    target: 'All Members',
    created_at: '2026-07-15 10:30',
  },
  {
    id: 'notif-702',
    title: 'UI/UX Access Codes Issued',
    description: 'Please check your registered WhatsApp or SMS for custom enrollment passcode key.',
    icon: 'Award',
    target: 'All Members',
    created_at: '2026-07-14 16:45',
  },
  {
    id: 'notif-703',
    title: 'Urgent Aadhaar Verification Alert',
    description: 'Several records have mismatched civil data. Please re-upload your primary id scan copy.',
    icon: 'Bell',
    target: 'Group',
    created_at: '2026-07-12 09:15',
  },
];

export const MOCK_ACTIVITY_LOGS: AdminActivityLog[] = [
  {
    id: 'act-801',
    title: 'Beneficiary Registered',
    description: 'Admin registered Meera Gavit from Dhadgaon village to NGO Database.',
    timestamp: '10 minutes ago',
    icon: 'Users',
  },
  {
    id: 'act-802',
    title: 'Course Updated',
    description: 'Instructor Savita Phadke updated syllabus for UI/UX Web Design.',
    timestamp: '2 hours ago',
    icon: 'BookOpen',
  },
  {
    id: 'act-803',
    title: 'Coupon Activated',
    description: "System created and activated sponsor coupon code: 'AGRIFREE'.",
    timestamp: '1 day ago',
    icon: 'Award',
  },
  {
    id: 'act-804',
    title: 'Member Enrollment Modified',
    description: "Admin shifted Sanjay Shinde state program state to 'Inactive'.",
    timestamp: '2 days ago',
    icon: 'Bell',
  },
  {
    id: 'act-805',
    title: 'Security Rules Hardened',
    description: 'Enforced mandatory alphanumeric password requirements for teacher accounts.',
    timestamp: '3 days ago',
    icon: 'Users',
  },
];

export const MOCK_WEBSITE_CONTENT: WebsiteContent = {
  courses: [
    { id: 'web-c1', title: 'Organic Cultivation Course', description: 'Our flag agricultural training modules.', visibility: 'Both Pages', image: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&q=80&w=400' },
    { id: 'web-c2', title: 'Figma & Layout Mastery', description: 'Learn web and application layouts with visual balance.', visibility: 'Homepage Only', image: 'https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?auto=format&fit=crop&q=80&w=400' },
  ],
  programs: [
    { id: 'web-p1', title: 'Satara Rural Skills Enhancement Program', description: 'Funded by state sponsorship initiatives.', visibility: 'Both Pages' },
    { id: 'web-p2', title: 'Women Vocational Empowerment Drive', description: 'Free tailoring and retailing modules in Sangli district.', visibility: 'Programs Page Only' },
  ],
  leadership: [
    { id: 'web-l1', title: 'Shri. Prakash Deshmukh', description: 'Executive Director & NGO Founder', visibility: 'Both Pages' },
    { id: 'web-l2', title: 'Smt. Shaila Patil', description: 'Rural Education Coordinator', visibility: 'Both Pages' },
  ],
  testimonials: [
    { id: 'web-t1', title: 'Priya Patil', description: 'This course completely transformed my outlook. I earned state placement!', visibility: 'Both Pages' },
    { id: 'web-t2', title: 'Vijay Rathod', description: 'The organic farming guidelines helped us increase output by 20%. Thank you, Compassion!', visibility: 'Homepage Only' },
  ],
  contact_social: {
    address: 'Plot 42, Civil Lines, Behind Satara Court, Satara, Maharashtra - 415001',
    email: 'contact@compassionglobal.org',
    phone: '+91 2162 234567',
    facebook: 'https://facebook.com/compassionglobal',
    twitter: 'https://twitter.com/compassionglb',
    linkedin: 'https://linkedin.com/company/compassionglobal',
    instagram: 'https://instagram.com/compassionglobal',
  },
  gallery: [
    { id: 'web-g1', title: 'Farming Workshop 2026', visibility: 'Homepage Only' },
    { id: 'web-g2', title: 'Graduation Ceremony Batch A', visibility: 'Both Pages' },
  ],
  resources: [
    { id: 'web-r1', title: 'NGO Brochure PDF', description: 'Complete organizational brief.', visibility: 'Both Pages' },
    { id: 'web-r2', title: 'Organic Farming Quick Guide', description: 'Composting manual in Marathi/Hindi.', visibility: 'Both Pages' },
  ],
  locations: [
    { id: 'web-loc1', title: 'Satara Krishi Center', description: 'Rural farm and hybrid coaching space.', visibility: 'Both Pages' },
    { id: 'web-loc2', title: 'Nandurbar Paramedic Clinic', description: 'Healthcare lab setup.', visibility: 'Both Pages' },
  ],
};

export const DEFAULT_ADMIN_SETTINGS: AdminSettings = {
  general: {
    siteName: 'CompassionGlobal NGO Portal',
    description: 'Empowering rural youth and farmers with modern technological, agricultural, and business skills.',
    logo: 'CompassionGlobal',
    timezone: 'Asia/Kolkata (GMT+05:30)',
    language: 'en',
  },
  email: {
    smtpHost: 'smtp.compassionglobal.org',
    smtpPort: '587',
    smtpUser: 'noreply@compassionglobal.org',
    senderName: 'NGO Skill Coordinator',
    senderEmail: 'coordinator@compassionglobal.org',
    notifNewRegistration: true,
    notifApplication: true,
    notifCertificate: true,
  },
  security: {
    pwMinLength: 8,
    pwRequiresSpecial: true,
    pwRequiresNumber: true,
    pwRequiresUppercase: true,
    sessionTimeout: 30,
    maxLoginAttempts: 5,
    enable2FA: false,
  },
  appearance: {
    theme: 'Light',
    brandColor: '#2563EB',
    sidebarCollapsedDefault: false,
    fontSize: 'Medium',
  },
  system: {
    maintenanceMode: false,
    maintenanceMessage: 'System is undergoing a scheduled database synchronization backup. We will be online shortly.',
    autoBackup: true,
    backupFrequency: 'Daily',
    backupRetention: 30,
  },
};
