// Canonical allowlist of site setting keys. Derived from the admin Settings UI
// (settings-client.tsx CATEGORY_KEYS). The bulk upsert route rejects any key
// not present here, so security-relevant settings cannot be injected ad hoc.

export const SITE_SETTING_KEYS: Record<string, string> = {
  "general.siteName": 'general',
  "general.logo": 'general',
  "general.description": 'general',
  "general.timezone": 'general',
  "general.language": 'general',
  "home_hero_heading": 'homepage',
  "home_hero_description": 'homepage',
  "home_mission_text": 'homepage',
  "home_vision_text": 'homepage',
  "home_stat_volunteers": 'homepage',
  "home_stat_families_helped": 'homepage',
  "home_stat_programs": 'homepage',
  "home_stat_families_supported": 'homepage',
  "home_stat_students": 'homepage',
  "home_stat_trees": 'homepage',
  "home_efficiency": 'homepage',
  "home_lives_impacted": 'homepage',
  "home_transparency_statement": 'homepage',
  "home_report_title": 'homepage',
  "home_report_funds": 'homepage',
  "home_report_efficiency": 'homepage',
  "home_report_summary": 'homepage',
  "home_impact_story_title": 'homepage',
  "home_impact_story_description": 'homepage',
  "home_impact_story_image": 'homepage',
  "home_impact_story_author": 'homepage',
  "home_impact_story_body": 'homepage',
  "home_impact_story_quote": 'homepage',
  "home_newsletter_heading": 'homepage',
  "home_newsletter_description": 'homepage',
  "about_stat_countries": 'about',
  "about_stat_aid": 'about',
  "about_stat_lives": 'about',
  "about_stat_audits": 'about',
  "about_values_heading": 'about',
  "about_values_description": 'about',
  "about_value_1_title": 'about',
  "about_value_1_description": 'about',
  "about_value_1_label": 'about',
  "about_value_2_title": 'about',
  "about_value_2_description": 'about',
  "about_value_2_label": 'about',
  "about_value_3_title": 'about',
  "about_value_3_description": 'about',
  "about_value_3_label": 'about',
  "about_value_4_title": 'about',
  "about_value_4_description": 'about',
  "about_value_4_label": 'about',
  "legal_registration_statement": 'legal',
  "donate_tax_note": 'legal',
  "email.smtpHost": 'email',
  "email.smtpPort": 'email',
  "email.smtpUser": 'email',
  "email.smtpPass": 'email',
  "email.senderName": 'email',
  "email.senderEmail": 'email',
  "email.notifNewRegistration": 'email',
  "email.notifApplication": 'email',
  "email.notifCertificate": 'email',
  "security.pwMinLength": 'security',
  "security.pwRequiresSpecial": 'security',
  "security.pwRequiresNumber": 'security',
  "security.pwRequiresUppercase": 'security',
  "security.sessionTimeout": 'security',
  "security.maxLoginAttempts": 'security',
  "security.enable2FA": 'security',
  "appearance.theme": 'appearance',
  "appearance.brandColor": 'appearance',
  "appearance.sidebarCollapsedDefault": 'appearance',
  "appearance.fontSize": 'appearance',
  "system.maintenanceMode": 'system',
  "system.maintenanceMessage": 'system',
  "system.autoBackup": 'system',
  "system.backupFrequency": 'system',
  "system.backupRetention": 'system',
};

export function isAllowedSettingKey(key: string): boolean {
  return Object.prototype.hasOwnProperty.call(SITE_SETTING_KEYS, key);
}

export function getSettingCategory(key: string): string | undefined {
  return SITE_SETTING_KEYS[key];
}
